### ISSUE TITLE
Belgium08 test always fails

### ISSUE THREAD

**Issue by rubensworks** [comunica/manifest-ldf-tests#2]
It looks like Comunica tries to request https://comunica.github.io/manifest-ldf-tests/sparql/belgium08/779e7c1e5df3bbf54cc277a690ae0801a5491644, while this file does not exist.

@ManuDeBuck Any idea whether this is a Comunica or a recorder issue?

**Comment by ManuDeBuck** [comment]
This was (luckily) just a typo in the manifest-test source. This issue is fixed in: https://github.com/comunica/manifest-ldf-tests/commit/cc0f64882a1f892c2eefa33080d9bba80625941f. Sorry for the waiting.

**Comment by ManuDeBuck** [comment]
This was (luckily) just a typo in the manifest-test source. This issue is fixed in: https://github.com/comunica/manifest-ldf-tests/commit/cc0f64882a1f892c2eefa33080d9bba80625941f. Sorry for the waiting.
