### ISSUE TITLE
simple03 is non-deterministic

### ISSUE THREAD

**Issue by rubensworks** [comunica/manifest-ldf-tests#3]
https://comunica.github.io/manifest-ldf-tests/sparql/sparql-manifest.ttl#simple03 is defined as follows:

```sparql
SELECT * WHERE { ?s ?p <http://dbpedia.org/resource/Belgium>. ?s ?p ?o } LIMIT 5
```

Since results are streaming, and order is undefined, a limit of 5 may sometimes produce different results.

This is exactly what is sometimes happening with Comunica.

Possible solutions would be:

1. Add an `ORDER BY` to the query (downside: this will make the query evaluation a lot slower)
2. Make the query more selective so that it produces fewer results, so that an `ORDER BY` can be done efficiently.

(Also: Both DBpedia TPF and SPARQL are included as source in this query. It would be better if this was based on two distinct sources, with different datasets behind them)

**Comment by ManuDeBuck** [comment]
Indeed. Didn't think this one through! Will have a look at this.
